socks_listen: "0.0.0.0:1080"
device_listen: "0.0.0.0:443"
tls_cert: "configs/server.crt"
tls_key: "configs/server.key"
socks_password: "secret"
device_wait: 30s
connect_wait: 30s
heartbeat_ttl: 90s
proxy_idle_timeout: 30s
socks_local_resolve: false
max_clients: 30000
max_clients_per_device: 32
log:
  level: info
  file_path: logs/xproxy.log
  max_size: 1024
  max_backups: 3
  max_age: 7
  compress: true