socks_listen: "127.0.0.1:1080"
device_listen: "0.0.0.0:8443"
tls_cert: "configs/server.crt"
tls_key: "configs/server.key"
socks_password: "secret"
device_wait: 30s
connect_wait: 30s
heartbeat_ttl: 90s
